version: 2
project_name: powerline-go

before:
  hooks:
    - go mod download

builds:
  - main: ./  cmd/powerline-go/main.go
    binary: powerline-go
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
      - "386"
    goos:
      - darwin
      - linux
      - windows
      - freebsd
      - netbsd
      - openbsd
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: openbsd
        goarch: arm
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format: binary

checksum:
  name_template: 'sha256sums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^hack:'
      - '^chore:'
      - '^Merge pull request'

nfpms:
- maintainer: Marco Siebecke <marco@siebecke.se>
  description: powerline-go fork
  homepage: https://github.com/gentoomaniac/powerline-go
  license: MIT
  formats:
  - deb
